dist: Xenial
language: python
python: "3.7"
before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
  - sudo apt update
  - sudo apt install -y clang clang-format
  - npm install -g markdownlint-cli
  - pip install Sultan
  - pip install scan-build
install: 
  - 'if [ -n "$RTI_MIN_PACKAGE_URL" ]; then ./resources/travis/linux_install.py; fi'
script:
  - 'if [ -n "$RTI_MIN_PACKAGE_URL" ]; then ./resources/travis/linux_script.py; fi'
