dist: Xenial
language: python
python: "3.7"
before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
  - sudo apt update
  - sudo apt install -y clang clang-format
  - git config --global clangFormat.binary clang-format-10
  - npm install -g markdownlint-cli
  - pip install Sultan
  - pip install scan-build
  - pip install black
install: 
  - 'if [ -n "$RTI_MIN_PACKAGE_URL" ]; then resources/travis/linux_install.py; fi'
script:
  - 'if [ -n "$RTI_MIN_PACKAGE_URL" ]; then resources/travis/linux_static_analysis.py; fi'
  - 'if [ -n "$TRAVIS_COMMIT_RANGE" ]; then resources/travis/linux_format.py --commit-range $TRAVIS_COMMIT_RANGE ; else resources/travis/linux_format.py --commit $TRAVIS_COMMIT; fi'
